"""Central public identity strings so the working codename is replaceable."""

PRODUCT_NAME = "NoTUG"
PRODUCT_SHORT_NAME = "NoTUG"
EXPANSION = "No Touching Unless Granted"
CLI_NAME = "notug"
PACKAGE_NAME = "notug-protocol"
MODULE_NAME = "notug_protocol"
VAULT_DIRECTORY_NAME = "notug-protocol"
VERSION = "0.1.0"
DESKTOP_PRODUCT_NAME = "Leucoform"
DESKTOP_TAGLINE = "Leucoform, powered by NoTUG"
BRANCH_NAMESPACE = CLI_NAME
EVIDENCE_REF_NAMESPACE = f"refs/{BRANCH_NAMESPACE}"
POLICY_FILENAME = f"{CLI_NAME}.toml"
COMMIT_TRAILER_PREFIX = PRODUCT_SHORT_NAME
COMMIT_EMAIL = f"{CLI_NAME}@localhost.invalid"
HOME_ENVIRONMENT_VARIABLE = f"{PRODUCT_SHORT_NAME.upper()}_HOME"
AGENT_SESSION_ENVIRONMENT_VARIABLE = f"{PRODUCT_SHORT_NAME.upper()}_AGENT_SESSION"
VALIDATION_CONTEXT_ENVIRONMENT_VARIABLE = f"{PRODUCT_SHORT_NAME.upper()}_VALIDATION_CONTEXT"
VAULT_FORMAT = f"{CLI_NAME}-local-vault-v1"
MUTATION_LOCK_ACTIVE = "Mutation Lock: active"
TUG_GENERATED = "Tug Signal generated"
HUMAN_GRANT_REQUIRED = "Human grant required"
CHECKOUT_UNCHANGED = "Protected checkout unchanged"
DIVERGENCE_DETECTED = "Provenance divergence detected"
GRANT_BOUND = "Grant bound to Tug Signal"
INTEGRATION_CREATED = "Integration branch created"
